const IT = [
/*00*/"Frecuencia",
/*01*/"D_Frecuencia",
/*02*/"Voltaje_Nominal",
/*03*/"Voltaje_AB",
/*05*/"Voltaje_CA",
/*04*/"Voltaje_BC",
/*06*/"Voltaje_A",
/*07*/"Voltaje_B",
/*08*/"Voltaje_C",
/*09*/"Voltaje_N",
/*10*/"Desbalance_Voltaje",
/*11*/"SAG",
/*12*/"SWELL",
/*13*/"Backspin",
/*14*/"Voltaje Backspin",
/*15*/"Corriente_A",
/*16*/"Corriente_B",
/*17*/"Corriente_C",
/*18*/"Corriente_N",
/*19*/"Corriente_Total",
/*20*/"Desbalance_Corriente",
/*21*/"Potencia_Aparente A",
/*22*/"Potencia_Aparente B",
/*23*/"Potencia_Aparente C",
/*24*/"Potencia_Aparente Total",
/*25*/"Potencia_Activa A",
/*26*/"Potencia_Activa B",
/*27*/"Potencia_Activa C",
/*28*/"Potencia_Activa Total",
/*29*/"Potencia_Reactiva A",
/*30*/"Potencia_Reactiva B",
/*31*/"Potencia_Reactiva C",
/*32*/"Potencia_Reactiva Total",
/*33*/"Factor_Potencia",
/*34*/"Factor_Desplazamiento",
/*35*/"K_Factor",
/*36*/"THDV",
/*37*/"THDV_3",
/*38*/"THDV_5",
/*39*/"THDV_7",
/*40*/"THDV_11",
/*41*/"THDV_13",
/*42*/"THDV_17",
/*43*/"THDV_19",
/*44*/"THDV_23",
/*45*/"THDV_25",
/*46*/"THDV_29",
/*47*/"THDV_31",
/*48*/"THDV_35",
/*49*/"THDI",
/*50*/"THDI_3",
/*51*/"THDI_5",
/*52*/"THDI_7",
/*53*/"THDI_11",
/*54*/"THDI_13",
/*55*/"THDI_17",
/*56*/"THDI_19",
/*57*/"THDI_23",
/*58*/"THDI_25",
/*59*/"THDI_29",
/*60*/"THDI_31",
/*61*/"THDI_35",
/*62*/"Type_Comm",
/*63*/"Angulo_VA",
/*64*/"Angulo_VB",
/*65*/"Angulo_IA",
/*66*/"Angulo_IB",
/*67*/"Angulo_IC", 
];

const INFODATAEQ = [
/*00*/"Empresa",
/*01*/"Marca_VSD",
/*02*/"Pozo",
/*03*/"Modelo",
/*04*/"Serial",
/*05*/"Marca_Bomba",
/*06*/"Marca_Transformador_Hexafasico",
/*07*/"",
/*08*/"Fecha_Energia_Acumulada",
/*09*/"",
/*10*/"Marca_Transformador_Elevador",
/*11*/"Potencia_Transformador_Hexafasico",
/*12*/"Corriente_Transformador_Hexafasico",
/*13*/"Voltaje_Transformador_Hexafasico",
/*14*/"Potencia_VSD",
/*15*/"Corriente_VSD",
/*16*/"Voltaje_VSD",
/*17*/"Potencia_Transformador_Elevador",
/*18*/"Corriente_Transformador_Elevador",
/*19*/"Voltaje_Transformador_Elevador",
/*20*/"Voltaje_Transformador_Elevador",
/*21*/"Potencia_Bomba",
/*22*/"Corriente_Bomba",
/*23*/"Voltaje_Bomba",
];

const INFOVERSION = [
    "Version",
    "Modulos",
    "Tipo_VSD",
];

const commands = {
    "IT": IT,
    "OV": IT,
    "OM": IT,
    "INFODATAEQ": INFODATAEQ,
    "INFOVERSION": INFOVERSION
}

module.exports = commands;